"""new models

Revision ID: 1e56b37bd4a0
Revises: 7bc336342485
Create Date: 2023-07-08 23:13:23.608861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e56b37bd4a0'
down_revision = '7bc336342485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trader_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_days_return_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('numbers_of_trades', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_months_return_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profit_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('loss_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trading_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('followers', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trader_profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('followers')
        batch_op.drop_column('trading_hours')
        batch_op.drop_column('loss_percentage')
        batch_op.drop_column('profit_percentage')
        batch_op.drop_column('last_months_return_usd')
        batch_op.drop_column('numbers_of_trades')
        batch_op.drop_column('last_days_return_usd')

    # ### end Alembic commands ###
