"""new models

Revision ID: 29acfc43aa51
Revises: 1a9990f52276
Create Date: 2023-07-04 22:56:48.577671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29acfc43aa51'
down_revision = '1a9990f52276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bitcoin_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('holding_balance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('available_balance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pending_balance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('locked_balance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('wallet_deposit_address', sa.String(), nullable=True))

    with op.batch_alter_table('ethereum_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('holding_balance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('available_balance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pending_balance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('locked_balance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('wallet_deposit_address', sa.String(), nullable=True))

    with op.batch_alter_table('tether_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('holding_balance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('available_balance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pending_balance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('locked_balance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('wallet_deposit_address', sa.String(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thether_account_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bitcoin_account_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ethereum_account_user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('transactions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ethereum_account', ['ethereum_account_user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'bitcoin_account', ['bitcoin_account_user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'tether_account', ['thether_account_user_id'], ['user_id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transactions_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('ethereum_account_user_id')
        batch_op.drop_column('bitcoin_account_user_id')
        batch_op.drop_column('thether_account_user_id')

    with op.batch_alter_table('tether_account', schema=None) as batch_op:
        batch_op.drop_column('wallet_deposit_address')
        batch_op.drop_column('locked_balance')
        batch_op.drop_column('pending_balance')
        batch_op.drop_column('available_balance')
        batch_op.drop_column('holding_balance')
        batch_op.drop_column('vat')
        batch_op.drop_column('fee')
        batch_op.drop_column('exchange_rate')

    with op.batch_alter_table('ethereum_account', schema=None) as batch_op:
        batch_op.drop_column('wallet_deposit_address')
        batch_op.drop_column('locked_balance')
        batch_op.drop_column('pending_balance')
        batch_op.drop_column('available_balance')
        batch_op.drop_column('holding_balance')
        batch_op.drop_column('vat')
        batch_op.drop_column('fee')
        batch_op.drop_column('exchange_rate')

    with op.batch_alter_table('bitcoin_account', schema=None) as batch_op:
        batch_op.drop_column('wallet_deposit_address')
        batch_op.drop_column('locked_balance')
        batch_op.drop_column('pending_balance')
        batch_op.drop_column('available_balance')
        batch_op.drop_column('holding_balance')
        batch_op.drop_column('vat')
        batch_op.drop_column('fee')
        batch_op.drop_column('exchange_rate')

    # ### end Alembic commands ###
