"""new models

Revision ID: 365681210372
Revises: 1e56b37bd4a0
Create Date: 2023-07-08 23:25:43.133324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365681210372'
down_revision = '1e56b37bd4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trader_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trader_profile', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
