"""new models

Revision ID: 9768642a41ae
Revises: f148ea82ee73
Create Date: 2023-07-10 22:11:03.817956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9768642a41ae'
down_revision = 'f148ea82ee73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bitcoin_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_withdrawable_amount', sa.Float(), nullable=True))

    with op.batch_alter_table('ethereum_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_withdrawable_amount', sa.Float(), nullable=True))

    with op.batch_alter_table('tether_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_withdrawable_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tether_account', schema=None) as batch_op:
        batch_op.drop_column('min_withdrawable_amount')

    with op.batch_alter_table('ethereum_account', schema=None) as batch_op:
        batch_op.drop_column('min_withdrawable_amount')

    with op.batch_alter_table('bitcoin_account', schema=None) as batch_op:
        batch_op.drop_column('min_withdrawable_amount')

    # ### end Alembic commands ###
