"""new models

Revision ID: bf2a36a3268b
Revises: c5ea991e3ec9
Create Date: 2023-07-06 22:01:24.413841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2a36a3268b'
down_revision = 'c5ea991e3ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tether_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_erc', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trc_tether_wallet_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('erc_tether_wallet_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ethereum_wallet_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bitcoin_wallet_address', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bitcoin_wallet_address')
        batch_op.drop_column('ethereum_wallet_address')
        batch_op.drop_column('erc_tether_wallet_address')
        batch_op.drop_column('trc_tether_wallet_address')

    with op.batch_alter_table('tether_account', schema=None) as batch_op:
        batch_op.drop_column('address_erc')

    # ### end Alembic commands ###
